### PR TITLE
Allow lazy verbose_name translations

### PR DESCRIPTION
**Pull request by benjaoming**
This fixes an issue here: https://github.com/rtfd/readthedocs.org/issues/2495

I'm not sure if this is the preferred way of doing things, nor am I sure if this project is 2+3? But hopefully this can assist getting the issue solved... feel free to close this PR and implement your own way :)

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. Thanks for this. 

What exactly is broken? (Can we get a test showing the faulty behaviour?)

**Comment by carltongibson** [comment]
This is just #558 right?

**Comment by benjaoming** [comment]
Yup, that's #558 - as RTD uses your `master` branch, I didn't anticipate a fix to exist :)

**Comment by carltongibson** [comment]
OK. Let me merge that now then... 😀


(The other issues just require using the `.qs` property — as we're not aliasing those anymore — or pin to 0.15.x — which will raise a dev warning.)

(1.0 is worth having.)

Happy to help if any other issues come up.

**Comment by benjaoming** [comment]
Thanks, I'll forward the advice :)

**Pull request closed without merging**
