### PR TITLE
Simply versions in Tox

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by rpkilby** [comment]
We should probably add py35,py36 to the django22 matrix

**Comment by rpkilby** [comment]
Also, need to drop py34 from travis config

**Comment by ad-m** [comment]
@rpkilby , done!

**Comment by carltongibson** [comment]
Ah, I think we both did exactly the same thing. I beat you by 17 seconds. 😀

**Comment by ad-m** [comment]
I do not agree :smile:  I pushed first, then you force-push & overwrite commit, then I had to correct the typo and again force-push again.

**Comment by rpkilby** [comment]
👊 _Force Push Wars_ 👊 

😄

**Comment by carltongibson** [comment]
Oops. I think I just corrected the typo again. 😄

(I think we're right now...)

**Pull request merged**
