### PR TITLE
setup.py - add PyPI trove classifiers

### PR DESCRIPTION
**Pull request by adamchainz**
They're [[ https://pypi.python.org/pypi?%3Aaction=list_classifiers | official classifiers ]] and can be used to help users to upgrade their Django version. Just have to remember to keep them up to date!

### CODE REVIEW

**Comment by rpkilby** [comment]
> can be used to help users to upgrade their Django version.

Do the classifiers have an effect beyond package browsing in pypi?

**Comment by adamchainz** [comment]
They're a lot more prominent [on Warehouse](https://pypi.org/search/?q=&o=&c=Framework+%3A%3A+Django+%3A%3A+1.10) and could be used by other tools. I think it's nice to provide more metadata that can be worked with.

**Comment by rpkilby** [comment]
Btw, it looks like the Django classifier is already present [here](https://github.com/carltongibson/django-filter/blob/0.15.2/setup.py#L55). 

I'm kind of inclined to follow DRF's lead here ([setup.py](https://github.com/tomchristie/django-rest-framework/blob/3.4.7/setup.py#L94-L104)).

**Comment by adamchainz** [comment]
Sorry I didn't see it at the bottom there because everything else was in alphabetical order.

Up to you, though a counter-example would be Django's own `django-contrib-comments`: https://github.com/django/django-contrib-comments/blob/master/setup.py 🎅

**Comment by carltongibson** [comment]
I'm going to pass on this for now. 

We follow [Django's supported versions](https://www.djangoproject.com/download/#supported-versions). So do many of the big projects out there. I think any tooling needs be sensitive to that. 

IMO, keeping this sort of stuff up to date is more work than the benefit provides; despite the Warehouse example I don't see the classifiers (as yet) being much used. 

I'm happy to review this at some future time: maybe the tooling comes on.

**Pull request closed without merging**
