### PR TITLE
Fix inverted skipIf for CrispyFormsCompatTests tests

### PR DESCRIPTION
**Pull request by mgorny**
The test is being wrongly skipped when crispy_forms are installed
rather than the other way around.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
OK, well this **looks** right, but I think we need to dig deeper... 

[Lastest build on main, for py39-latest has 7 skipped](https://github.com/carltongibson/django-filter/runs/3707195722?check_suite_focus=true#step:6:88)

[Same run for this PR has 9 skipped](https://github.com/carltongibson/django-filter/pull/1444/checks?check_run_id=3707196356#step:6:88). 

That seems the wrong way round, [given that crispy-forms is in the list of installed packages](https://github.com/carltongibson/django-filter/runs/3707195722?check_suite_focus=true#step:6:75)? 🤔

**Comment by mgorny** [comment]
It's because of this:

```
def is_crispy():
    return 'crispy_forms' in settings.INSTALLED_APPS and crispy_forms
```

This creates a circular dep since `crispy_forms` are added to `INSTALLED_APPS` only if `is_crispy` is True. I suppose the easiest way around it would be to check on `crispy_forms` directly from the test. I'll add a commit doing that.

**Comment by mgorny** [comment]
That said, I've tried to make the tests more verbose but it seems that `-v 2` doesn't affect actual test output when using `runtests.py` for some reason. It works fine when calling `django-admin test ...` directly.

**Comment by mgorny** [comment]
Rebased.

**Comment by carltongibson** [comment]
OK, great. Thanks

**Review by carltongibson — APPROVED** [review]

**Comment by mgorny** [comment]
Thanks!

**Pull request merged**
