### PR TITLE
[1.1] Deprecations for 2.0

### PR DESCRIPTION
**Pull request by rpkilby**
- [x] Deprecate `Meta.together`
- [x] Rename `Filter.name` => `Filter.field_name`
- [x] Deprecation note for `FILTERS_STRICTNESS`, `Meta.strict`, `FilterSet.strict`

### CODE REVIEW

**Comment by rpkilby** [comment]
Ach. Why do you forsake my python 2???

**Comment by rpkilby** [comment]
I am perplexed - this does not fail locally for me.

**Comment by carltongibson** [comment]
Give me a sec. I will give it a run.

**Comment by carltongibson** [comment]
Right, I'm perplexed too. 

Travis has two failures. (One for each test). 

I'm getting a failure just for the second. 

```
................................................F..........................................................s..x...ss..x..x..........................................................................................................................................................................................................................s.........................sss..................................................................................
======================================================================
FAIL: test_filter_strictness (tests.test_deprecations.DeprecatedSettingsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/carlton/Documents/Django-Stack/django-filter/tests/test_deprecations.py", line 37, in test_filter_strictness
    self.assertEqual(len(w), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 451 tests in 1.274s

FAILED (failures=1, skipped=7, expected failures=3)
```

Given that it's exactly the same as the first, that doesn't make much sense to me.

**Comment by rpkilby** [comment]
I'll have to come back to this tomorrow - I can't figure out what's going on :/

**Comment by rpkilby** [comment]
I'm still not entirely sure why the tests were failing on CI and not locally, but the issue was related to a bad stacklevel on a few of the warnings.

**Comment by carltongibson** [comment]
@rpkilby: 

> ... strictness  ... there will be no migration path for strictness, so v1.1 will always raise warnings for the user.

Either of: 

* Let people silence the warning. 
* Merge the rest but just DON'T add the deprecation warning for strictness: Folks are just going to have to notice this in the migration guide when upgrading. (I think that's OK — it's the smoothest migration path — no reason it has to be totally frictionless if that's not OK.)

**Comment by rpkilby** [comment]
The latter seems preferable. The release notes can make mention of the strictness deprecations instead.

**Comment by rpkilby** [comment]
Alright, this should be done. I've removed the strictness warnings, but left the deprecation note.

**Pull request merged**
