### PR TITLE
Fix #506

### LINKED ISSUE #506: 0.15.1 crashes if imported
Because of this:
https://github.com/carltongibson/django-filter/blob/master/django_filters/rest_framework/backends.py#L37

Django looks for a DjangoTemplates engine in the settings, and I don't use Django templates, I use Jinja2.

```
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/rest_framework_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/rest_framework_filters/filterset.py", line 11, in <module>
    from django_filters import filterset, rest_framework
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/django_filters/rest_framework/__init__.py", line 3, in <module>
    from .backends import DjangoFilterBackend
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/django_filters/rest_framework/backends.py", line 37, in <module>
    template_default = Template(FILTER_TEMPLATE)
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/django/template/base.py", line 184, in __init__
    engine = Engine.get_default()
  File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/django/template/engine.py", line 81, in get_default
    "No DjangoTemplates backend is configured.")
django.core.exceptions.ImproperlyConfigured: No DjangoTemplates backend is configured.
```

Thank god for tests :)

### PR DESCRIPTION
**Pull request by rpkilby**

### CODE REVIEW

**Comment by carltongibson** [comment]
Why doesn't this build fail? https://travis-ci.org/carltongibson/django-filter/builds/163654156

**Comment by rpkilby** [comment]
I'm confused - it's failing locally

**Comment by carltongibson** [comment]
I'll run it. LGTM though...

**Comment by rpkilby** [comment]
Running this locally w/ tox, all of the builds for Django 1.10 fail correctly. (DTL backend configuration error). I really don't know why this doesn't work on travis.

**Comment by carltongibson** [comment]
> Running this locally w/ tox, all of the builds for Django 1.10 fail correctly

Yeah. Me too.

Fancy updating `CHANGES.rst` for a 1.5.2 today?

**Comment by rpkilby** [comment]
Like so?

**Pull request merged**
