### PR TITLE
Improve performance on ManyToMany chained filters 

### LINKED ISSUE #745: Problem with chained filters and Django ORM
As related in the issue #537, the Django ORM generate duplicated INNER JOINS for each `.filter()` .

For example:
`Model.objecs.filter(table1__attr1=value1).filter(table1__attr2=value2)`

The built query is:

```sql
SELECT *
FROM model_table
INNER JOIN table1 ON (model_table.id = table1.model_table_id)
INNER JOIN table1 T5 ON (model_table.id = T5.model_table_id)
WHERE (table1.attr1=value1 AND T5.attr2=value2)
```
But the **correct** query should be:

```sql
SELECT *
FROM model_table
INNER JOIN table1 ON (model_table.id = table1.model_table_id)
WHERE (table1.attr1=value1 AND table1.attr2=value2)
```

The first query may return unwanted or unexpected results.

Reading the code I found the method `def qs(self)` in class `BaseFilterSet` from the file **filterset.py** and I realized the following workflow:

1. Get all the model objects using `qs = self.queryset.all()`
2. Iterates in the list of declared filters (fields)
3. In other words, for each field is done the same as `qs = self.queryset.filter(field_n=value_n) `, what causes the described problem.
4. When the iteration finishes, the queryset (**qs**) is returned

The solution that I've developed for the chained filters problem is:

```python
    def qs(self):
        kwargs = {}
        if not hasattr(self, '_qs'):
            if not self.is_bound:
                self._qs = self.queryset.all()
                return self._qs

            if not self.form.is_valid():
                if self.strict == STRICTNESS.RAISE_VALIDATION_ERROR:
                    raise forms.ValidationError(self.form.errors)
                elif self.strict == STRICTNESS.RETURN_NO_RESULTS:
                    self._qs = self.queryset.none()
                    return self._qs
                # else STRICTNESS.IGNORE...  ignoring

            # start with all the results and filter from there
            qs = self.queryset.all()
            for name, filter_ in six.iteritems(self.filters):
                value = self.form.cleaned_data.get(name)

                if value is not None and value:  # valid & clean data
                    # If all o these conditions are true, it means that
                    # field (filter_) is filtering the queryset
                    # So, it must be added to the filtering dict
                    kwargs[filter_.name] = value

            # The same as qs.filter(filter_.name1=value1, filter_.name2=value2, ...)
            self._qs = qs.filter(**kwargs)

        return self._qs
```

Instead of making queries for each field, all of them are stored in a dictionary and the queryset is filtered only one time using this dict.

What do you think about this solution? Would it break other parts of the code?

### PR DESCRIPTION
**Pull request by varnion**
I was experiencing the issue @eduardocalil reported on #745. At the time, the fix proposed by him wasnt accepted because:

1) it broke a [test](https://travis-ci.org/carltongibson/django-filter/jobs/259777166).
2) because the problem is more a django ORM issue than django-filter.

I can't comment on *2*, but at least *1* dont block this PR anymore. The error was caused by currently unsupported versions of DRF.

### CODE REVIEW

**Comment by varnion** [comment]
After inspecting the tests I realized they are not actually running.

**Comment by rpkilby** [comment]
> After inspecting the tests I realized they are not actually running.

Can you point out which tests aren't running?

**Comment by carltongibson** [comment]
Hi. 

This isn't a performance issue. The _issue_ is that over M2M relations, this: 

```
Blog.objects.filter(entry__headline__contains='Lennon', entry__pub_date__year=2008)
```

is not semantically equivalent to this: 

```
Blog.objects.filter(entry__headline__contains='Lennon').filter(entry__pub_date__year=2008)
```

[as documented in the Queries topic doc](https://docs.djangoproject.com/en/2.1/topics/db/queries/#spanning-multi-valued-relationships).

The _solution_ here is **NOT** to get involved in ORM Dark Magic™. 

Rather, you need to be creating a (multi-)filter that takes the (e.g. two) parameters and applies them in a single step. 

The addition to Django Filter for this is: 

* Document the pattern
* Add a filter class that allows declarative declaration. 

I'll leave this open for now as a reminder.

**Comment by varnion** [comment]
@rpkilby about the tests being skipped, it seems that all of them were skipped :scream: 
this happened not only on this [PR](https://travis-ci.org/carltongibson/django-filter/jobs/431241166) but also on [master](https://travis-ci.org/carltongibson/django-filter/jobs/427569012).

**Comment by varnion** [comment]
@rpkilby [this](https://github.com/carltongibson/django-filter/pull/977/commits/cbd686acf94be1630cf9373e75b58206d559fcf5) is the change that I made to make detox run and detect that I was breaking lots of tests

**Comment by rpkilby** [comment]
Yikes. This looks like a huge bug in tox/detox. Those exceptions should not result in passing builds.

@carltongibson - might be a good reason to enable the coverage status check?

**Comment by rpkilby** [comment]
I would recommend that we ditch detox in favor of regular tox. Honestly, I don't think we get much from parallelizing tox. The tests are pretty fast - most of the build time is just setting up the Travis container.

**Comment by rpkilby** [comment]
Sure.

**Comment by rpkilby** [comment]
lol I never got around to making that PR.

**Comment by rpkilby** [comment]
@carltongibson - I think you can close this now given the PR.

**Comment by carltongibson** [comment]
I left this open to document the pattern and/or add a multi-parameter filter base class or such. 
(Have had ===0 time to look at that. 🙄)

**Comment by rpkilby** [comment]
Ah - thought you meant about the tox/detox thing. 👍

**Comment by carltongibson** [comment]
Moved documentation issue into #1020

**Pull request closed without merging**
