### PR TITLE
Update filter_for_lookup override docs

### LINKED ISSUE #776: `filter_for_lookup` cannot be overriden
Summary
------------
`filter_for_lookup`  is a class method, but is called in the metaclass, so when `super` is called, the class does not exist yet.

So, contrary to what is in the documentation, it's not "really" possible to override this method.

You'll find below different important library versions, the steps to reproduce the error, and a temporary workaround

Versions
--------
Python: 2.7.9
Django:1.11.4
django-filter: 1.0.4

Steps to reproduce:
-------------------

This is the simplest example. You can type it in a console and type "enter" at the end, the error will occur.

```python
from django.contrib.auth.models import User
from django_filters import FilterSet

class MyFilter(FilterSet):
    class Meta:
        model = User
        fields = ['username']

    @classmethod
    def filter_for_lookup(cls, f, lookup_type):
        return super(MyFilter, cls).filter_for_lookup(f, lookup_type)
```

This produces  directly, at the time the class is created, this error:

```python
NameError                                 Traceback (most recent call last)
/path/to/local-code
----> 1 class MyFilter(FilterSet):
      2     class Meta:
      3         model = User
      4         fields = ['gender']
      5 

/path/to/django_filters/filterset.pyc in __new__(cls, name, bases, attrs)
     84         new_class = super(FilterSetMetaclass, cls).__new__(cls, name, bases, attrs)
     85         new_class._meta = FilterSetOptions(getattr(new_class, 'Meta', None))
---> 86         new_class.base_filters = new_class.get_filters()
     87 
     88         return new_class

/path/to/django_filters/filterset.pyc in get_filters(cls)
    304 
    305                 if field is not None:
--> 306                     filters[filter_name] = cls.filter_for_field(field, field_name, lookup_expr)
    307 
    308         # filter out declared filters

/path/to/django_filters/filterset.pyc in filter_for_field(cls, f, name, lookup_expr)
    328         }
    329 
--> 330         filter_class, params = cls.filter_for_lookup(f, lookup_type)
    331         default.update(params)
    332 

/path/to/local-code in filter_for_lookup(cls, f, lookup_type)
      6     @classmethod
      7     def filter_for_lookup(cls, f, lookup_type):
----> 8         return super(MyFilter, cls).filter_for_lookup(f, lookup_type)
      9 

NameError: global name 'MyFilter' is not defined
```

Workaround
---------

The simplest workaround - but not a clean solution - is to not use `super()` but hard-code the `FilterSet` class (it will of course not work if the filter class inherits from many parents):

```python

    @classmethod
    def filter_for_lookup(cls, f, lookup_type):
        return FilterSet.filter_for_lookup(f, lookup_type)
```

### PR DESCRIPTION
**Pull request by rpkilby**
This should fix #776. Also adds a test demonstrating the expected override behavior.

### CODE REVIEW

**Comment by rpkilby** [comment]
This is more complicated than what it seemed at first glance. Django seems to have dealt with the same issue (ref django/django#7653).

**Comment by carltongibson** [comment]
@rpkilby Can you identify the Python 3.6 change that addressed this? (Out of interest...)

**Comment by rpkilby** [comment]
Yep. https://bugs.python.org/issue23722

**Comment by rpkilby** [comment]
So, Django was experiencing a separate problem. They overrode the incoming `attrs` with a new dictionary, accidentally excluding `__classcell__`. This in turn broke argument-less `super()` calls. django-filter does not have this problem, since we only add to the `attrs` dict. 

What I need to determine is if it's possible to alter the metaclass initialization somehow, such that the python 2/3 compatible `super(ClassName, cls)` works again.

**Comment by rpkilby** [comment]
Oh, right - this is a `NameError`. The class name simply doesn't exist yet, so `super(MyFilter, cls)` fails accordingly. `super()` sidesteps the issue because it isn't referencing the class name. 

What I need to determine is if it's possible to somehow enable argument-less `super()` on python 3.3 - 3.5

**Comment by carltongibson** [comment]
My favourite bit of the Python thread is Guido going:

> Please don't respond arguing the "clearly" part, just go ahead and do it. :-)

**Comment by rpkilby** [comment]
So, this affects all of the classmethods defined on the `FilterSet`. The solution here is to refactor `base_filters` such that we don't call any of the FIlterSet's classmethods during class creation. As mentioned in the other thread, we can work around the issue by defining the overridden classmethods on an intermediate class, but this is not desirable.

**Comment by rpkilby** [comment]
I'm thinking that we can update `base_filters` to become a class-level property that caches itself on first access. This would defer calling the classmethods until after class creation is finished.

**Comment by carltongibson** [comment]
I’m a bit reticent to jump through a lot of hoops over this. 

“Just use Python 3.6” strikes me as pretty reasonable in 2017Q3, especially given an easy workaround

**Comment by rpkilby** [comment]
Agreed, although I'm also okay with a minimal, non-API breaking change. Right now, we're calling classmethods on a class before it has been fully created, which does feel a bit weird.

**Comment by carltongibson** [comment]
Sure, but the intent is right. So given it was enabled by 3.6 I’m happy to say that’s where we should head...

**Comment by rpkilby** [comment]
Yep, calling `.get_filters()` and related classmethods performs a certain amount of validation during class creation. eg, broken `Meta.fields` will immediately raise some kind of exception. Deferring when `.get_filters()` is called would also defer when these exceptions are raised.

I'll work on an alternative docs PR.

**Pull request closed without merging**
