### PR TITLE
Fix Empty Queryset for Unbound Filter Form

### PR DESCRIPTION
**Pull request by deanpienaar**
Fix for #930 

### Changes
1. If the filter form is not bound. return what the list view would return by default.
2. Fix the values of a test that were incorrect but passing.

### CODE REVIEW

**Comment by deanpienaar** [comment]
@carltongibson No certain why the build is failing but seems to be the same issue as with #985.

**Comment by carltongibson** [comment]
Hey @deanpienaar. OK thanks. I'll sort it out. 👍

**Comment by rpkilby** [comment]
We might need to upgrade/downgrade tox/detox here. There has been a lot of development going on in that project, and there have been some breaking changes here and there.

**Comment by rpkilby** [comment]
Actually, I'm kind of inclined to just remove detox altogether. The test suite itself is fairly quick, and we don't gain much by parallelizing the tox test runs. The majority of the time spent in each Travis job is just standing up the VM.

**Comment by carltongibson** [comment]
Yep. And for me, I’m happy to click through. It makes the results the same in CI as locally. 

(Wasn’t sure we needed 3x “latest” builds when I was looking at it today...)

**Comment by deanpienaar** [comment]
Hi @carltongibson. Thanks! Seems the build is passing now.

**Comment by carltongibson** [comment]
Hi @deanpienaar. I'm working for v2.1 over the holidays. (Next week essentially.) This'll be part of that.

**Comment by rpkilby** [comment]
I'm also eventually getting around to reviewing this+the original issue. I had worked on this over the Thanksgiving holiday, but something caused a hard drive partition failure and I lost all of my data 🤦‍♂️

**Comment by rpkilby** [comment]
iirc, this was only part of the issue. There was more work to be done revolving around the `strict` parameter. Can't remember if those two are intrinsically tied together.

**Comment by deanpienaar** [comment]
@rpkilby Sorry about your hard drive 😢.

>Can't remember if those two are intrinsically tied together.

It seems they are. I took the approach of "If the filterset form isn't bound, it shouldn't be doing anything at all". Not sure if that's what is preferred.

**Pull request closed without merging**
