### PR TITLE
Improve german translation

### PR DESCRIPTION
**Pull request by christianwgd**
Fixed some wrong translations to german language, improved some others

### CODE REVIEW

**Comment by gatsinski** [comment]
I think that you also need the binary file generated by `compilemessages`. They are part of the repo.

**Comment by christianwgd** [comment]
Sorry, sometimes the .mo files are not part of repo and are created during release build. But here it is.

**Comment by gatsinski** [comment]
Yes, and I believe they should always be part of the build process. This will avoid issues like #1320.

**Comment by gatsinski** [comment]
Yes, and I believe they should always be part of the build process. This will avoid issues like #1320 but this is another topic.

**Review by carltongibson — APPROVED** [review]
Hi @christianwgd — thanks for this! 👍

**Pull request merged**
