### PR TITLE
Run tests against Python 3.9

### PR DESCRIPTION
**Pull request by michael-k**
The tests are currently failing.  I couldn't figure out why, but I haven't spent much time looking into it.

If someone else wants to address this, go for it.  Otherwise I'll free some time before Python 3.9.0 is released and try to fix this.

----

Python 3.9.0 final is expected on Monday, 2020-10-05, see https://www.python.org/dev/peps/pep-0596/#schedule

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hey @michael-k. Whilst we're here, can we adjust the workflow to not cancel the other jobs in the matrix on the first failure (since "still passes on 3.8" is useful info)?

**Comment by carltongibson** [comment]
@michael-k This diff seems to do the job: 

```diff
diff --git a/tests/utils.py b/tests/utils.py
index e11410e..3a4bd25 100644
--- a/tests/utils.py
+++ b/tests/utils.py
@@ -3,13 +3,19 @@ from unittest import mock
 from django.db import models
 
 
+class QuerySet(models.QuerySet):
+
+    def __bool__(self):
+        return True
+
+
 class MockQuerySet:
     """
     Generate a mock that is suitably similar to a QuerySet
     """
 
     def __new__(self):
-        m = mock.Mock(spec_set=models.QuerySet())
+        m = mock.Mock(spec_set=QuerySet())
         m.filter.return_value = m
         m.all.return_value = m
         return m
```

**Comment by michael-k** [comment]
> This diff seems to do the job:

\o/

The tests are green now :)

**Review by carltongibson — APPROVED** [review]
Super. Let's have it. Thanks!

**Pull request merged**
