### PR TITLE
Another attempt at filter to support 1,2,3 syntax

### PR DESCRIPTION
**Pull request by zoidbergwill**
Replaces https://github.com/alex/django-filter/pull/259

@carltongibson How does this look?

### CODE REVIEW

**Comment by carltongibson** [comment]
Looks good. Away from the computer so need to check it later. 

Two questions:

1. Are the field and filter classes just conveniences? Could we get away without them using the widget keyword arg? Do they need docs?
2. Why are we checking for MultiValueDict and using getlist in value_from_datadict?  Is the idea not that the widget allows passing a list through a single value, rather than repeating the parameter name? Avoiding this would eliminate the need to convert back to a string later; why's it there?

**Comment by zoidbergwill** [comment]
1. Will try get some tests working using the `extras.widget` stuff.

2. It was just convenience in case someone does a request with multiple query parameters, but I guess it would need smarter logic to actually support it properly, in the expected way.

**Comment by zoidbergwill** [comment]
Hi @carltongibson 

1. I'm battling to use the widget stuff. It's not using the widget when using the filterset. I think it's the same issue I had last time. I might be doing something wrong.

2. Will commit code for dropping the `MultiValueDict` supprot.

**Comment by carltongibson** [comment]
I'd be inclined to keep it as simple as possible, at least to begin.

**Comment by carltongibson** [comment]
> I'm battling to use the widget stuff. It's not using the widget when using the filterset. I think it's the same issue I had last time. I might be doing something wrong.

Paste the code you're using. I'm thinking if you declare the filter to use the new `CSVFilter` it should work...

**Comment by carltongibson** [comment]
(Will review this fully after Christmas now)

**Comment by carltongibson** [comment]
Thanks for the effort!

**Comment by zoidbergwill** [comment]
I'll give it a couple more tries, and then paste my code. Thanks for the review, @carltongibson

**Comment by dursk** [comment]
:+1: would be great to have this

**Pull request closed without merging**
