### PR TITLE
Update german Translation and init inlang Config

### PR DESCRIPTION
**Pull request by jannesblobel**
Hi,
Changes

- added an inlang.config.js file to the root of the repo
- updated and fix German translations

I saw your german translation was broken. To make it easier for me to contribute to your translation, I added the tool [inlang/inlang](https://github.com/inlang/inlang). I am opening this PR as a draft to discuss the tool. Maintainers or contributors would have no overhead as inlang is built on git. No accounts (login with GitHub), no sync, and no pipelines are required. Contributions open a PR.

Would a UI over the translations in this repo be of benefit to the Django-filter community? There are a couple of issues regarding this topic. [Translations #1512
](https://github.com/carltongibson/django-filter/discussions/1512) or [PR #1516 ](https://github.com/carltongibson/django-filter/pull/1516) 

Issue  #1510 is still open, although you merged the PR #1515. I guess you can reduce your issue counter and can close this issue :) 

You can try it out on my fork and post your feedback under this draft.
https://inlang.com/editor/github.com/jannesblobel/django-filter

You can see a short preview in the video. While translating, I noticed that some translations still need to be included; maybe someone from the community can correct them. 
Need to include translation in this Language. 
es_AR = Spanish Argentina, 
zh_CN = Chinese

The PR is theoretically ready for review.

https://user-images.githubusercontent.com/72493222/215597007-e1ff0236-5437-4227-9256-9fefb9cd71aa.mp4

### CODE REVIEW

**Comment by jannesblobel** [comment]
Oh wow, sorry for the video quality.  I need to increase the recording settings 
, sorry :? :/

**Comment by carltongibson** [comment]
HI @jannesblobel this looks interesting. Thanks. 

I'm looking to do an update in time for Django 4.2 so timely. 

I haven't heard of this tool before... 👀

**Comment by carltongibson** [comment]
Hi @jannesblobel — thanks for this! 

I've added django-filter to Weblate https://hosted.weblate.org/projects/django-filter/django-filter/ — we're hoping to move Django to this, so I'd rather use the same tools if possible. 

I've updated the message files too, so if you wanted to contribute your translations there, that would be amazing! 

I will close this PR though. 
Thanks again!

**Comment by jannesblobel** [comment]
@carltongibson , 
I'm sorry for not getting back to you sooner. I have moved and have not yet found the time to reply 

It is interesting to see how many Django projects use Weblate. Is there a specific reason for this movement? 
Perhaps you find a couple of minutes to give me a short introduction to the benefits of Weblate and why you are using it. 
 
 PS: The German translation should have been added/suggested via Weblate. :)

**Comment by carltongibson** [comment]
Hi @jannesblobel -- there are two topics: updating the translations, and then the tool for doing that. It's been on the agenda to look at moving Django's translations to Weblate for a while -- there's been an amount of discussion of the best tool -- and when looking at the new release for django-filter it's a good opportunity to use it too.

**Comment by jannesblobel** [comment]
Thank you for this insides. 
Before I opened this draft, 
I checked to see if there was a discussion on this topic to post my idea of using inlang for translations there. Unfortunately, is no discussion of this topic in the discussions/Issues, or I could not find it(also possible). 

I would be very interested to know each tool's pros and cons. Can you link the discussion/issue for me? :)

**Pull request closed without merging**
