### PR TITLE
added rangewidget to docs

### PR DESCRIPTION
**Pull request by v1k45**
`RangeWidget` was not documented anywhere in the docs which makes it hard to figure out what widget to use with `RangeFilter`

### CODE REVIEW

**Comment by v1k45** [comment]
Why are the tests failing? I just made changes in the docs :worried:

**Comment by rpkilby** [comment]
Whoops. I recently reenabled some date range tests, but it looks like the month and year tests had some date-dependent issues. Should be fixed by #400.

**Comment by rpkilby** [comment]
Assuming all is well with that PR, you'll want to rebase once it's merged in.

**Comment by v1k45** [comment]
Sure, will do :+1:

**Comment by carltongibson** [comment]
@v1k45 #400 is merged

**Comment by v1k45** [comment]
@carltongibson tests are passing now :)

**Comment by ad-m** [comment]
LGTM

**Pull request merged**
