### PR TITLE
Add tests case for translation of OrderingFilter

### PR DESCRIPTION
**Pull request by ad-m**
Hello,

I observe that there is a lack of support for translation in OrderingFilter. I am unable to fix that now, but I prepared a tests case which might be helpful to fix that. 

```
$ tox -e py34-django19-restframework34
(…)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/django-filter/tests/test_filtering.py", line 1749, in test_ordering_translation_all_ovverride
    (u'-username', u'XYZXYZ')])
AssertionError: Lists differ: [('',[13 chars], ('username', 'BLABLA'), ('-username', 'BLABLA (descending)')] != [('',[13 chars], ('username', 'BLABLA'), ('-username', 'XYZXYZ')]

First differing element 2:
('-username', 'BLABLA (descending)')
('-username', 'XYZXYZ')

+ [('', '---------'), ('username', 'BLABLA'), ('-username', 'XYZXYZ')]
- [('', '---------'),
-  ('username', 'BLABLA'),
-  ('-username', 'BLABLA (descending)')]

======================================================================
FAIL: test_ordering_translation_default_label (tests.test_filtering.OrderingFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/django-filter/tests/test_filtering.py", line 1707, in test_ordering_translation_default_label
    (u'-username', u'Nazwa użytkownika (malejący)')])
AssertionError: Lists differ: [('',[24 chars]e', 'Username'), ('-username', 'Username (descending)')] != [('',[24 chars]e', 'Nazwa użytkownika'), ('-username', 'Nazwa[21 chars]y)')]

First differing element 1:
('username', 'Username')
('username', 'Nazwa użytkownika')

  [('', '---------'),
-  ('username', 'Username'),
-  ('-username', 'Username (descending)')]
+  ('username', 'Nazwa użytkownika'),
+  ('-username', 'Nazwa użytkownika (malejący)')]

======================================================================
FAIL: test_ordering_translation_override_label (tests.test_filtering.OrderingFilterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/django-filter/tests/test_filtering.py", line 1727, in test_ordering_translation_override_label
    (u'-username', u'BLABLA (malejący)')])
AssertionError: Lists differ: [('',[13 chars], ('username', 'BLABLA'), ('-username', 'BLABLA (descending)')] != [('',[13 chars], ('username', 'BLABLA'), ('-username', 'BLABLA (malejący)')]

First differing element 2:
('-username', 'BLABLA (descending)')
('-username', 'BLABLA (malejący)')

+ [('', '---------'), ('username', 'BLABLA'), ('-username', 'BLABLA (malejący)')]
- [('', '---------'),
-  ('username', 'BLABLA'),
-  ('-username', 'BLABLA (descending)')]
```

### CODE REVIEW

**Comment by carltongibson** [comment]
@ad-m Nice. Good. Thanks.

**Comment by rpkilby** [comment]
I've started working on this - part of the reason the tests fail is that `django_filters` isn't added to `INSTALLED_APPS` in the test settings, so the localization files aren't found.

**Comment by ad-m** [comment]
So docs should be updated to mention ````INSTALLED_APPS``` changes.

**Comment by rpkilby** [comment]
The docs already instruct users to add 'django-filter' to the `INSTALLED_APPS`. This is just the test settings. Also, see #545, which does add a note about the translation files.

**Comment by ad-m** [comment]
@rpkilby , thank you. I deleted my comments immediately after check that. I memorized that somebody wrote there about lack requirements of update ```INSTALLED_APPS```, so I think docs mention that. I am sorry this comment is not required.

**Comment by rpkilby** [comment]
Other notes:
- The translation file has "malejąco" instead of "malejący"
- Adding a field label for descending options (eg, '-username') is not supported. 

I'm about to submit a PR - thanks for the initial test cases.

**Pull request closed without merging**
