### PR TITLE
add Azure Pipelines

### PR DESCRIPTION
**Pull request by vtbassmatt**

### CODE REVIEW

**Comment by vtbassmatt** [comment]
I left out Python 3.4 so that the build would run successfully. I see that it's failing in what looks like the same way on Travis, so it should be fine to re-enable it once you're satisfied with how other things look.

**Comment by rpkilby** [comment]
This looks like an issue with detox, which hasn't kept up with tox development and has some incompatibilities. I've created a PR to revert back to using plain tox. You could try doing the same here.

**Comment by rpkilby** [comment]
Just out of curiosity, what's the plan here? Are we moving away from Travis in favor of Azure Pipelines?

**Comment by carltongibson** [comment]
We’re giving it a run. No plan to turn off Travis just yet, but I want to see what the Azure offering is all about.

**Comment by rpkilby** [comment]
Is it possible to consolidate the TEST-*.xml files into a single file or directory? The number of  files is fine for CI since you don't need to worry about cleaning up, but for local development, one file per test case is a bit much.

**Comment by carltongibson** [comment]
Yes, looks like there are options: https://github.com/xmlrunner/unittest-xml-reporting#django

**Comment by rpkilby** [comment]
maybe `TEST_OUTPUT_DIR = '.xmlcoverage'`?

**Comment by rpkilby** [comment]
Aaaggh. I've been banging my head against a wall for half an hour as to why the `TEST_OUTPUT_DIR` env variable wasn't being obeyed. Was tox misbehaving? Was xmlrunner misbehaving?

> ### Django support
>
> In order to plug `XMLTestRunner` to a Django project, add the following to your `settings.py`:

🤦‍♂️

**Pull request merged**
