### PR TITLE
Fix filterset multiple inheritance bug

### PR DESCRIPTION
**Pull request by rpkilby**
Declared filter resolution was mostly copied from DRF. This fixes a multiple inheritance bug described in https://github.com/encode/django-rest-framework/pull/6980

### CODE REVIEW

**Comment by carltongibson** [comment]
We sure we’re not changing a behaviour from the dawn of time here? 🙂

**Comment by rpkilby** [comment]
It looks like the original behavior was mirrored in this PR.

https://github.com/carltongibson/django-filter/blob/62516ad143764fa6b0fb617f9761560918270efd/django_filters/filterset.py#L33-L40

However, I refactored `get_declared_filters` at some point and iirc I copied the code largely from DRF. Currently looking into this.

**Comment by rpkilby** [comment]
oh wait, I read that completely wrong.

**Comment by rpkilby** [comment]
Either way, like DRF, I think the original behavior is incorrect. I just don't think this multiple inheritance use case is an incredibly common, which is why it hasn't been raised here yet (and why it hasn't seen much attention in DRF either).

**Comment by carltongibson** [comment]
OK... Let me look into it. I want to be 100% sure. (And we'll need a release note stating the BC change.)

**Comment by rpkilby** [comment]
Just as a note, this PR needs to be updated, pending review of the DRF PR.

**Comment by rpkilby** [comment]
@carltongibson updated this from the DRF pr. This should be good to go assuming tests pass.

**Pull request merged**
