### PR TITLE
Updated packaging to use pyproject.toml and Flit.

### PR DESCRIPTION
**Pull request by deronnax**
Because setup.py is deprecated and setup.cfg is one step toward pyprojects.toml.

### CODE REVIEW

**Comment by deronnax** [comment]
@carltongibson can I have a workflow run please?

**Comment by carltongibson** [comment]
It's all pyproject.toml these days no?
🤔

I've been using Flit on other projects, and will likely move to that at some point.

**Comment by deronnax** [comment]
there you go. The flit build seems broken though:
```
 flit build                                                                                                                                                                                                             k3d-mycluster
Traceback (most recent call last):
  File "/Users/mathieu/.local/bin/flit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/flit/lib/python3.11/site-packages/flit/__init__.py", line 191, in main
    main(args.ini_file, formats=set(args.format or []),
  File "/Users/mathieu/.local/pipx/venvs/flit/lib/python3.11/site-packages/flit/build.py", line 45, in main
    sb = SdistBuilder.from_ini_path(ini_file, use_vcs=use_vcs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/flit/lib/python3.11/site-packages/flit/sdist.py", line 163, in from_ini_path
    inst = super().from_ini_path(ini_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/flit/lib/python3.11/site-packages/flit_core/sdist.py", line 92, in from_ini_path
    module = common.Module(ini_info.module, srcdir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mathieu/.local/pipx/venvs/flit/lib/python3.11/site-packages/flit_core/common.py", line 59, in __init__
    raise ValueError("No file/folder found for module {}".format(name))
ValueError: No file/folder found for module django_filter
```

`python -m build` works, nevertheless

**Comment by deronnax** [comment]
Hmmm OK we were affected by [this particularity of flit](https://flit.pypa.io/en/stable/pyproject_toml.html#pyproject-module), I got it fixed. 
We are good to go :)

**Comment by deronnax** [comment]
@carltongibson can I have a workflow run please?

**Comment by carltongibson** [comment]
@deronnax Thanks for this. Just so you know, life is pretty full-on right now, so I will likely be a week or so to get to this. Thanks!

**Comment by deronnax** [comment]
OK. I go in holiday for 2 tweeks next Friday, so I won't bother you too much. Btw, I think it is ready to be merged, but you do you :)

**Comment by deronnax** [comment]
let's merge :) ?

**Comment by carltongibson** [comment]
Nearly to it @deronnax. Thanks. 🙏

**Review by carltongibson — APPROVED** [review]
Hi @deronnax Thanks for this. Really great. I pushed some edits, squashed, rebased, and added an extra workaround for #1605 (unrelated). 

🎁

**Pull request merged**
