### PR TITLE
Set default value of filterset data to MultiValueDict

### PR DESCRIPTION
**Pull request by sgordon16**
fix for issue #1633

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Hi @sgordon16 — just to let you know, I'm not ignoring this. 

I think it looks great. (I can't think of any issues, unless folks are doing weird `isinstance` checks...) 

I'm slowly edging towards a release, and this will be part of that.

**Comment by carltongibson** [comment]
If you had capacity though, adding a test that demonstrates the change in behaviour would be handy. Thanks.

**Comment by sgordon16** [comment]
> If you had capacity though, adding a test that demonstrates the change in behaviour would be handy. Thanks.

Done

**Comment by sgordon16** [comment]
I also just want to point out that this is what Django does in the `BaseForm` class [here](https://github.com/django/django/blob/c991602ce5798385261381025c06698d7fd30dc5/django/forms/forms.py#L86).

**Comment by carltongibson** [comment]
@sgordon16 Yes, it's certainly _correct_. I would have merged it already, but I want to play with a couple of things in the shell, and just haven't had time for that yet. 

🎁

**Review by carltongibson — APPROVED** [review]
OK, brilliant. Let's have it. Thanks @sgordon16 🎁

**Pull request merged**
