### PR TITLE
Adjust make_aware handling of DST start/end date

### PR DESCRIPTION
**Pull request by andreroggeri**
Shows error reported on #633

### CODE REVIEW

**Comment by andreroggeri** [comment]
Now I understand the problem.

When the DST ends, there are two equal datetimes with different timezones:

 - 2017-02-18 23:59-02:00
 - 2017-02-18 23:59-03:00

Do you think its ok to always use the latest one ? Since the `DateRangeFilter` try to get the biggest range possible.

**Comment by carltongibson** [comment]
OK. Good. 

It looks as if `handle_timezone` should take the extra parameter to pass to `make_aware`. 

Unless there's an argument as to why going on, I don't think there's a great answer to "should this be `True` or `False` by default?" — it's always going to be use specific (No?)

I guess `DateRangeField` needs an extra attribute. Default this to `False`. Allow users to set `True` on the field instance if they need to, in FilterSet's `__init__` say. 

Then docs and test for new behaviour. 


How did you hit this exactly? (What was the URL parameter that broke?)

**Comment by carltongibson** [comment]
Change of plan. 

* Make `handle_timezone()` an attribute on the class. Then we can just call it as is. `self.timezone_handler(...)`
* If a user needs to set the `is_dst` param they can use `functools.partial` on a per-instance basis. 
* Same fix to `IsoDateTimeField`
* Then just documenting that option.

**Comment by andreroggeri** [comment]
Since you can't pass the timezone info to the `DateRangeFilter` I think it should always be `False` (When is a end DST date).

This is a really edge case. I found it on my schedule system when trying to filter the schedules that ends today the error ocurred. The URL is `/v1/schedules/?status=0&date_1=2017-02-18`

**Comment by andreroggeri** [comment]
But what its the default value for `is_dst`?

**Comment by carltongibson** [comment]
> I think it should always be `False`

OK, the the simple fix is just to keep in contained to `handle_timezone` — but then it can't be controlled. 

> But what its the default value for is_dst?

If we make `handle_timezone()` an attribute on the field then there wouldn't be a default value but users could override it if they want. 



I think: 

* It will rarely come up
* Even more rarely will the overlap matter

So maybe we should just decide on `False` (but allow it to be accessible).

**Comment by andreroggeri** [comment]
I agree with you. 

I think that the default value, but customizable is the better path (But maybe more complicated) because things shouldn't break on some specific day. (It took me some time to find out what was wrong.)

I just found out that the same problem occurs on DRF. If you try to create a object with the datetime set to 18/02/2017 23:30 it throws the same error. 😢

**Comment by carltongibson** [comment]
Ping @tomchristie — Don't know if you want to do something or not...?

@andreroggeri Can you please move the function to the class as the discussion. Let's set `is_dst=False` — because at least then there won't be an error — but lets document that. 

Thanks for the report and the effort!

**Comment by tomchristie** [comment]
I don't get in detail exactly when this occurs in REST framework, but raising an exception doesn't sound like awful behavior in this case. Agree with @carltongibson re. customizable by overriding code, only.

**Comment by carltongibson** [comment]
@tomchristie: It'll come up in `DateTimeField.enforce_timezone()`, which in DRF **already is overridable**. 

> ... but raising an exception doesn't sound like awful behavior in this case

I'm in two minds. It's such an edge case — your `datetime` needs to fall in the transition from/to DTS — that no-one is ever going to think to cover it. 

Django has `is_dst=None` — allowing the error by default — but I'm half inclined towards covering the user's back... (???)

**Comment by tomchristie** [comment]
Raising a meaningful exception is kinda reasonable. Unless the user has UI specifically for choosing which of the two times they meant there's no way of guessing what the behavior should be. Hard to say that an app that gracefully reports an error in that case (and a backend engineer seeing an alert that someone really did hit that case IRL) is necessarily worse than hiding the case from the user.

**Comment by andreroggeri** [comment]
In `django-filter` case I think its safe to say that using `is_dst=False` is enough.

For DRF at least some warning on the docs indicating that this can happen (Very rarely, but still...).

For example: Searching on the docs for `AmbiguousTimeError` shows no result.

This is a edge case that can happen to all applications(on a very specific period) that are using timezones with DST.


@carltongibson do you still want to apply the changes ? I can update the PR at night.

**Comment by carltongibson** [comment]
@andreroggeri Yes — at the very least we should move the use of the `handle_timezone` method to a hook. I'm not yet settled on `None` vs `False`. 

I'm probably persuadable to a documented `False` — it I got a production error over it I'd probably think it could have been handled for me. (Though both ways seem arguable.)

**Comment by rpkilby** [comment]
Just my two cents:
- Adding `is_dst` with a value of `None` to `handle_timezone`'s signature makes sense to me. This is consistent with current behavior, and is technically correct. The datetime *is* ambiguous after all. If we were to override the default to `False`/`True`, it seems like the more appropriate place would be in the individual filters/fields. That said, I'm -0 on changing the default. 
- In terms of fixing `ISODateTimeField` - I'd leave it as is? Users are explicitly filtering by datetimes and should instead just add explicit timezone handling. Adding documentation would be a plus.
- Does `DateRangeFilter` need to be fixed? It does not make use of `handle_timezone`.
- Confusingly, `DateRangeField` is used by `DateFromToRangeFilter` instead of `DateRangeFilter`. I'm not sure if a blanket `False` value is sufficient here. `False` works in this instance because the DST changeover occurs at midnight and is the `to` value being filtered against. If this were the `from` value, should we not use `True` instead? What about when entering DST instead of exiting? Should they be flipped? There are multiple edge cases that need to be thought about.

**Comment by carltongibson** [comment]
OK. Thanks @rpkilby. Good input. 

Grrr. Timezones. 😤

"I want to be able to filter on a `DateField`" shouldn't require major user configuration. 

@andreroggeri You pointed to an SO answer providing an `is_dst` function. Do you think you could do something reasonable with that? 

If there's a simple enough solution we can include it. If it's too much we may need to (just) document it and accept that it's a known limitation.

**Comment by andreroggeri** [comment]
That function will tell us if the timezone has DST enabled or not, but I don't think it can help us here.

The easier path is to change the `handle_timezone` signature like @rpkilby said, adding the `is_dst` parameter defaulting to `None` (Keeping the default behavior).

Then change the `DateRangeField` to pass `is_dst` as `True` for `start_date` and `False` for `end_date`.

I think this way we can assure that we won't overflow to other day.

**Comment by carltongibson** [comment]
So `make_aware` passes `is_dst` off to `pytz.localize` where: 

> The` is_dst` parameter is ignored for most timestamps. It is only used during DST transition ambiguous periods to resulve that ambiguity. — [Docs](http://pytz.sourceforge.net/#tzinfo-api)

For every/most/many timezone(s) this we've got potential issues filtering on a `date` 2 times a year. That seems quite a lot to me. (It's not _that_ edge-case, as I way thinking when I had naive `datetimes` in mind.)

> Then change the DateRangeField to pass is_dst as True for start_date and False for end_date.
>
> I think this way we can assure that we won't overflow to other day.

That sounds right. We miss an hour the day DST starts/ends right? (My head hurts 🤕)

As long as we document that, with a test cases ideally, I think that's acceptable.

**Comment by andreroggeri** [comment]
Gotta figure out why this new test is failing.

**Comment by andreroggeri** [comment]
Sincerely DST are a very complex subject. 🙄 

DST starts at 2017-10-15 at midnight, at this time the clock will jump to 1am, so if we want to filter only this day, we need to filter from 2017-10-15 01:00 -02:00 - 2017-10-15 23:59 -02:00. `make_aware` should be doing the proper time shifting, but it doesn't works as the docs says.

>The pytz.NonExistentTimeError exception is raised if you try to make value aware during a DST transition such that the time never occurred (when entering into DST). Setting is_dst to True or False will avoid the exception by moving the hour backwards or forwards by 1 respectively. For example, is_dst=True would change a non-existent time of 2:30 to 1:30 and is_dst=False would change the time to 3:30. - [Docs](https://docs.djangoproject.com/en/1.11/ref/utils/#django.utils.timezone.make_aware)

My test:

```
tz = pytz.timezone('America/Sao_Paulo')
dt = datetime.datetime(2017, 10, 15 ,0 ,0)
print(make_aware(dt, tz))        --> NonExistentTimeError
print(make_aware(dt, tz, True))  --> 2017-10-15 00:00:00-02:00
print(make_aware(dt, tz, False)) --> 2017-10-15 00:00:00-03:00
```
From my understanding, the time should be shifted instead of the timezone, because those datetimes doesn't exists.

Am I right ?

BTW: I'm squashing my commits

**Comment by carltongibson** [comment]
> BTW: I think I made some mess when squashing my commits. 😢

🙂 Can you try to `rebase` on latest `develop`: that should sort out the commits. (We can squash at the end.)

I'll have a look at the rest later. (Thanks for the effort!)

**Comment by andreroggeri** [comment]
> Rebasing clears up the issues. (If you tick "Allow edits from maintainers" I can push to your branch.)

Checked

> is_dst was added in Django 1.9 so we'll need to do something about not passing the extra param for 1.8

I can add a check for that, but what should happen for those users ?

I'm starting to understand why noone handles this automatically :rofl: 
Maybe is better to only change the `handle_timezone` signature to support `is_dst` parameter and leave it to the users to implement the DST handling.

**Comment by carltongibson** [comment]
I rebased the branch (hint: `git reset --hard develop`) and added the compat shim for `make_aware`. 

The 1.8 tests are all failing with either `Ambiguous...` or `Nonexistent...` — that's expected We'll live with it. Anyone on 1.8 is welcome to upgrade. (It'd be beyond heroic to fix it.

* Please make the new tests **not** run on 1.8 ([`skipIf`](https://docs.python.org/3.6/library/unittest.html#unittest.skipIf))
* Please ensure an non-dat-transition case exists for 1.8, to cover the `make_aware` compat shim.

Then it's the logic for the test for 1.9+: `AssertionError: 3 != 2` 

And a note in the docs, of course.

**Comment by andreroggeri** [comment]
@carlosgoce The test that is failing I believe its an error. `make_aware` doesn't works as the docs says.

**Comment by andreroggeri** [comment]
Ok, passing `False` to `is_dst` brought the expected result. Can you please check if everything is ok ?

- [X] Skip new tests for 1.8
- [X] [Check if `make_aware` shim is being tested](https://github.com/carltongibson/django-filter/blob/develop/tests/test_filtering.py#L370)
- [X] Fix test failure
- [X] Add note in the docs

**Comment by carltongibson** [comment]
Looks good!

> ... passing False to is_dst brought the expected result...

Can you just reason that out for me please? Why wasn't `True` the correct value?

**Comment by andreroggeri** [comment]
Django docs says:

>The pytz.NonExistentTimeError exception is raised if you try to make  value aware during a DST transition such that the time never occurred (when entering into DST). Setting is_dst to True or False will avoid the exception by moving the hour backwards or forwards by 1 respectively. For example, is_dst=True would change a non-existent time of 2:30 to 1:30 and is_dst=False would change the time to 3:30.

So, passing `True` to `make_aware` would make the clock shift backwards. Because the DST sometimes occurs at midnight, doing this would lead to filtering data from the previous day (Thats why the tests were failing before).

Now, sending `False` makes the clock shift forward and doesn't overflow to other day. See the code below.

```
from datetime import datetime

import pytz
from django.utils.timezone import make_aware, make_naive

dt = datetime(2017, 10, 15)
tz = pytz.timezone('America/Sao_Paulo')

nodst = make_aware(dt, tz, False)
dst = make_aware(dt, tz, True)

print(dst)                      # 2017-10-15 00:00:00-02:00
print(nodst)                    # 2017-10-15 00:00:00-03:00
print(make_naive(dst, tz))      # 2017-10-14 23:00:00
print(make_naive(nodst, tz))    # 2017-10-15 01:00:00

```

**Comment by carltongibson** [comment]
@andreroggeri Thanks for this. Good work!

**Pull request merged**
