### PR TITLE
FilterSetMetaclass: add the not defined field name in TypeError

### PR DESCRIPTION
**Pull request by blueyed**
Tests are missing, but I wasn't sure how to approach it.  Please advice.

### CODE REVIEW

**Comment by carltongibson** [comment]
OK. Fine. I see what you've done there... Testing, right, yes... How did you come upon this? What made you need the fix?

**Comment by blueyed** [comment]
I wanted to be it more verbose, when it hit me.. :)

**Comment by carltongibson** [comment]
Right... So presumably you had a reproduce at some point... :)

**Comment by blueyed** [comment]
Yes, I see. You would use a field/filterset in this way.

It was more about the file/place and class of tests that it should be added to anyway - I could not find a similar one (e.g. using the class).

Do you require a test?
(it seems to not have been covered before, or not looked at the detail of the exception).
(And you're not using pytest btw)

**Comment by carltongibson** [comment]
I'd much prefer a test, even if one was lacking previously. I'm happy for you to use your judgement as to where one might go.

Yes. Pytest. That would be a big win.

The general approach is incremental improvement. The package has been around a while; it started well then fell somewhat into neglect. It's now doing OK. I'm hoping that continues. :-)

**Comment by blueyed** [comment]
Found a matching test by the help from `pdb.set_trace`.

**Comment by carltongibson** [comment]
👍

**Pull request merged**
