### PR TITLE
Added DEFAULT_AUTO_FIELD to test settings

### PR DESCRIPTION
**Pull request by smithdc1**

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Ok, yep. Thanks. Fancy rebasing?

**Comment by smithdc1** [comment]
Of course 👍. But first could you merge #1341?

(I'm also wonder if once that patch is in we could just re-run the tests?) 🤔

**Comment by carltongibson** [comment]
#1345
Alas, we have to rebase.

**Comment by smithdc1** [comment]
Hi Carlton -- all green ticks now :smile:

**Review by carltongibson — APPROVED** [review]
Super. Thanks @smithdc1 🙏

**Pull request merged**
