### PR TITLE
Update attributes

### PR DESCRIPTION
**Pull request by cfc603**

### CODE REVIEW

**Comment by rpkilby** [comment]
Hi @cfc603. This is incorrect. The old parameters were `filter_class` and `filter_fields`. The new parameters are `filterset_class` and `filterset_fields`.

**Comment by rpkilby** [comment]
@carltongibson - just noticing that the DRF docs are still using the outdated parameters. I thought this was updated, but apparently not.

**Comment by rpkilby** [comment]
Ah - just noticed that those changes were made just after the 3.9.1 release.

**Comment by carltongibson** [comment]
Hey @rpkilby. Yes. I made those the other day. They'll update when we release v3.9.2.

**Pull request closed without merging**
