### PR TITLE
Add settings for help_text in Filter

### PR DESCRIPTION
**Pull request by ad-m**
Hello,

In refference to #292 and discusion in #136 I wrote patch to provide settings for help_text in Filter.

Unfortunately, my English doesn't allow me write any docs.

Greetings,

### CODE REVIEW

**Comment by mik-laj** [comment]
Thanks a lot. This is what I need. You're my superhero. I'll make you dinner tomorrow if I'll be home

**Comment by jarekwg** [comment]
+1

**Comment by carltongibson** [comment]
This looks good but needs docs.

**Comment by mik-laj** [comment]
> Unfortunately, my English doesn't allow me write any docs.
Anyone willing to write documentation? My language is too weak

**Comment by carltongibson** [comment]
I'm happy to do it in principle but don't have the bandwidth right now. (Everyone's English seems fine from here.)

**Comment by carltongibson** [comment]
If this gets rebased I'm happy to merge this.

**Pull request closed without merging**
