### PR TITLE
Update rest_framework.txt

### PR DESCRIPTION
**Pull request by dequn**
DRF use `filter_class` or `filter_fields` for `filter_queryset`, not `filterset_class` or `filterset_fields` anymore.

### CODE REVIEW

**Comment by rpkilby** [comment]
Hi @dequn. You have this backwards. `filterset_class` and `filterset_fields` are the attribute names moving forward. `filter_class` and `filter_fields` are deprecated. You can see this here:

https://github.com/carltongibson/django-filter/blob/eef406c1ee429e3024999c8746d1ca5641185bf8/django_filters/rest_framework/backends.py#L42-L57

**Comment by rpkilby** [comment]
Note that the DRF docs are out of date, but will be updated/correct once DRF 3.9 is released.

**Comment by dequn** [comment]
> Hi @dequn. You have this backwards. `filterset_class` and `filterset_fields` are the attribute names moving forward. `filter_class` and `filter_fields` are deprecated. You can see this here:
> 
> [django-filter/django_filters/rest_framework/backends.py](https://github.com/carltongibson/django-filter/blob/eef406c1ee429e3024999c8746d1ca5641185bf8/django_filters/rest_framework/backends.py#L42-L57)
> 
> Lines 42 to 57 in [eef406c](/carltongibson/django-filter/commit/eef406c1ee429e3024999c8746d1ca5641185bf8)
> 
>  filterset_class = getattr(view, 'filterset_class', None) 
>  filterset_fields = getattr(view, 'filterset_fields', None) 
>   
>  # TODO: remove assertion in 2.1 
>  if filterset_class is None and hasattr(view, 'filter_class'): 
>      utils.deprecate( 
>          "`%s.filter_class` attribute should be renamed `filterset_class`." 
>          % view.__class__.__name__) 
>      filterset_class = getattr(view, 'filter_class', None) 
>   
>  # TODO: remove assertion in 2.1 
>  if filterset_fields is None and hasattr(view, 'filter_fields'): 
>      utils.deprecate( 
>          "`%s.filter_fields` attribute should be renamed `filterset_fields`." 
>          % view.__class__.__name__) 
>      filterset_fields = getattr(view, 'filter_fields', None)

OK, I'm using Django 2.0.5 and DRF 3.8.2, according to the doc `filterset_class` but it doesn't work.

**Comment by rpkilby** [comment]
What version of django-filter are you using. The version of DRF is mostly irrelevant here, as it's the `django_filters.rest_framework.DjangoFilterBackend` that defines those property names.

**Comment by dequn** [comment]
My django-filter version is 1.1.0, while my filter-backend is confirmedly right.

**Comment by rpkilby** [comment]
The change from `filter_class` to `filterset_class` was introduced in [v2.0](https://github.com/carltongibson/django-filter/releases/tag/2.0.0) (specifically, in #867). You should either upgrade, or reference the [v1.1.0 docs](https://django-filter.readthedocs.io/en/1.1.0/).

**Comment by dequn** [comment]
Thanks.

**Pull request closed without merging**
