### PR TITLE
Add filter_fields to FilterView

### PR DESCRIPTION
**Pull request by marctc**
If you have a FilterView only providng a model it could be useful to specify the fields you want to include to the filterset automatic construction.

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @marctc. 

This seems a reasonable addition. 

I'm kind of of the opinion that ever adding `exclude` to whatever API it first appeared in was an error. Setting `fields` is sometimes more effort but often a maintenance win in the long run. i.e. I wonder if we really want it here. What's your thought on that?

**Comment by marctc** [comment]
> I'm kind of of the opinion that ever adding exclude to whatever API it first appeared in was an error. 

I added because sometimes could be useful to exclude some fields and also to emulate the behaviour of `Meta` classes (like FieldSets, Serializers or Forms). But OTOH neither Django generic views nor DRF views had a an _exclude_ fields parameter. 

Should I remove then?

**Comment by carltongibson** [comment]
Yeah. I think so.

Also, it should probably be `filter_fields` to match DRF. 

Did you need this yourself? (The minimal `FilterSet` is quite small — I'm wondering if we need it at all.)

**Comment by marctc** [comment]
> Also, it should probably be filter_fields to match DRF.

I named it `filterset_fields` to keep coherence with `filterset_class` but you're right again.

> Did you need this yourself? (The minimal FilterSet is quite small — I'm wondering if we need it at all.)

What do you mean?

**Comment by carltongibson** [comment]
I mean, what prompted you to suggest this? 

I see the point of it but, also it's not hard to define `filterset_class`.

I'm wondering if it's something you actually wanted in real usage?

**Comment by marctc** [comment]
We are building an ERP for a client and there a lot of models and a lot of  FilterViews. Those views automatically renders the filter with all of the fields. If I want to exclude or explicity set a subset of fields, I have to define a filterset for each view. I'm a lazy developer, sorry :P

**Comment by carltongibson** [comment]
That's not a problem. :-) OK. It's reasonable. If you can make the changes we can have it. 

(I'm going to roll 1.0.2 this week, so it can join that.)

**Comment by marctc** [comment]
Thanks! Working on it.

**Comment by marctc** [comment]
Done

**Comment by carltongibson** [comment]
Awesome. Thanks.

**Pull request merged**
