### PR TITLE
Refactor read 'README.rst' file to use context manager for file handling

### PR DESCRIPTION
**Pull request by mahdirahimi1999**
### Description
This commit updates the read 'README.rst' file to use a context manager when opening the file, ensuring that the file is properly closed after it has been read. This improves the code's readability and helps to prevent potential resource leaks.

### CODE REVIEW

**Comment by mahdirahimi1999** [comment]
Please check this PR. @carltongibson

**Comment by mahdirahimi1999** [comment]
Please check this PR. @carltongibson

**Comment by carltongibson** [comment]
Hi @mahdirahimi1999. Yes I saw this. Not sure it's really worth it, given that setup.py is a single shot script. (And that it's likely time to move to pyproject.toml and, likely, flit)

**Comment by carltongibson** [comment]
Thanks but we moved to pyproject.toml

**Comment by mahdirahimi1999** [comment]
Ok, good luck
@carltongibson

**Pull request closed without merging**
