### PR TITLE
Update .gitignore from GitHub

### PR DESCRIPTION
**Pull request by rpkilby**
Mostly, I'm updating to add the common virtualenv paths, but in general, it seemed useful to update.

Two notes:
- All of the previous lines are included in the updated version.
- Usually, I'd prune unnecessary items (such as .scrapy), but opted not to because:
    1. they don't harm anything
    2. we'd have to prune future updates and.. meh? 

Yay/nay? I could also revert and just add the common virtualenv paths.

### CODE REVIEW

**Comment by blueyed** [comment]
> 1. they don't harm anything

- readability
- performance - while not critical, the more patterns the more overhead with git operations (also ripgrep)

So I'm -0, but feel free to pick the option with less maintenance.

**Comment by carltongibson** [comment]
Errr... @rpkilby 😃

My initial response, looking at the diff here, is 😱

`git clone ...` etc. How on earth do I end up with 95% of this in my working tree?

Why do we want this?

Ta.

**Comment by rpkilby** [comment]
Thought process was: 
- There are several common virtualenv paths that should probably be included in the .gitignore.
    (what I've done in the past, is just add these to the `.gitignore`, but not commit).
- There are other common tooling-related paths that should probably also be excluded. 
- So, update from GH's .gitignore.
- Then, question is if we should strip it down, or just copy+paste the entire thing. I realize there are several useless ignores doing the latter (e.g., `.scrapy/`)

I'm really open to whatever, no strong opinions on this.

**Comment by blueyed** [comment]
There is also a global gitignore (core.excludesfile), and you could add it to `.git/info/exclude`.
So having this more trimmed down is better.

**Comment by carltongibson** [comment]
OK, thanks. Erm... let's not. 🙂

More or less: _Use excludes_. 

Happy to consider **individual** items if the case can be made. 

Ta.

**Pull request closed without merging**
