### PR TITLE
Apply Black to entire code base and setup GitHub Action

### PR DESCRIPTION
**Pull request by smithdc1**
Hi @carltongibson 

Here is a pull request that adds Black to your project and introduces a GitHub action to test for adherence to this standard on push and pull requests. 
Hope this is helpful 🤞 

Edit: currently failing as needs to be applied more widely than just the project folder. Will take a look later.

### CODE REVIEW

**Comment by smithdc1** [comment]
Tests currently fail due to this issue with black. Will try again later in the year. 
https://github.com/psf/black/issues/1288

**Comment by carltongibson** [comment]
Hi @smithdc1 — I didn't look at the tests but... 

> Edit: currently failing as needs to be applied more widely than just the project folder. 

_¿Que?_ 🙂 What's the issue with just applying black to the code and tests? (Why do we need the toml file?)

Thanks for this. (I'm quite happy to have black in principle.)

**Comment by smithdc1** [comment]
Yes. My first attempt was too narrow. (crispy has tests in the project folder... Should change that).

Second attempt worked better but ran into lint checker not liking trailing commas. A current option is to remove them manually, as black doesn't re-add them. Otherwise we can wait for issue in black to be fixed.

Will explore further.

The toml file contains settings for [Black](https://black.readthedocs.io/en/stable/pyproject_toml.html#). I suspect more projects will use it in future as it's in pep518. Currently not all projects like having settings stored in here, and even those that apparently support it (isort) I've had issues getting to work.

So for now, black settings in toml others remain in existing files.

Thanks!


 https://www.python.org/dev/peps/pep-0518/

**Comment by smithdc1** [comment]
Hi @carltongibson 

hmmm. Having re-read what I've written above I don't think I explained myself very well.... As you say it just needs to be applied to the whole project consistently, I didn't do that originally hence why it failed.

In any case, here is my next attempt to get this working. 🤞

**Pull request closed without merging**
