### PR TITLE
Failing test for ChoiceField eagerly evaluating choices

### PR DESCRIPTION
**Pull request by craigds**
refs #1625

### CODE REVIEW

**Comment by craigds** [comment]
@carltongibson that should help^

In case it helps, that test passes when backported on top of 23.2 and fails with 23.3

**Comment by carltongibson** [comment]
Great. Thanks. Let me have a look. 👀

**Review by carltongibson — COMMENTED** [review]
Thanks @craigds. 

Since the callable is wrapped by the iterator, it's being cast to a list in super class (`forms.ChoiceField`):

```pytb
  File ".../django-filter/django_filters/fields.py", line 284, in choices
    super(ChoiceIteratorMixin, self.__class__).choices.__set__(self, value)
  File ".../django/forms/fields.py", line 880, in _set_choices
    value = list(value)
```

In order avoid that I think we need to bypass the superclass setter for Django<5.0. 

Something like: 

```diff
diff --git a/django_filters/fields.py b/django_filters/fields.py
index 3a34365..d6ac79c 100644
--- a/django_filters/fields.py
+++ b/django_filters/fields.py
@@ -275,13 +275,13 @@ class ChoiceIteratorMixin:
     def choices(self, value):
         if DJANGO_50:
             value = self.iterator(self, value)
+            # Simple `super()` syntax for calling a parent property setter is
+            # unsupported. See https://github.com/python/cpython/issues/59170
+            super(ChoiceIteratorMixin, self.__class__).choices.__set__(self, value)
         else:
             super()._set_choices(value)
             value = self.iterator(self, self._choices)
-
-        # Simple `super()` syntax for calling a parent property setter is
-        # unsupported. See https://github.com/python/cpython/issues/59170
-        super(ChoiceIteratorMixin, self.__class__).choices.__set__(self, value)
+            self._choices = self.widget.choices = value
 ```

Fancy trying that? 

cc @ngnpope

**Comment by ngnpope** [comment]
Thanks for the ping @carltongibson.

So, yes, it looks as though I was a little too optimistic there - your proposed patch looks like the right approach.

**Comment by craigds** [comment]
thanks, sorry I didn't get around to submitting a proper fix

**Comment by carltongibson** [comment]
No problem @craigds. The reproduce was the key thing. 🎁

**Pull request merged**
